### ISSUE TITLE
Creating Scheduled Shipments....

### ISSUE THREAD

**Issue by BradAtNoMatterWhere** [trexitycode/openapi#12]
I have been able to create post a Shipment with a scheduled pick up time and see it in the Sandbox, but the shipment shows up as a draft.  

I don't see anywhere in the API documentation where I can change the status of the shipment to "Scheduled", or anything in the Add Shipment API where I can set a variable to ensure that the shipment is properly set to "Scheduled".

If the parcel can be properly entered, I want it automatically scheduled and my user to then immediately see the shipping label, print it off and put it on a box.

Should I be using "Create Routing Request" instead?

Please advise.

**Comment by dschnare** [comment]
Hey @BradAtNoMatterWhere sorry for the delay in the response. When making an HTTP POST request to [Create a shipment](https://developers.trexity.com/reference/merchant-api/v1/#tag/Shipments/operation/createShipment) endpoint all you need to provide is a date for "pickupStartAt". The date needs to match the start of a pickup window in the [market](https://trexity.zendesk.com/hc/en-us/articles/16940024932627-Pickup-windows) you're creating a shipment in.

Afterwards, when retrieving the shipment with a HTTP GET request to the Get a shipment endpoint the shipment's "currentStatus" will in fact be "" (empty string) and "scheduledPostAt" will contain a timestamp. Our platform interprets the combination as being scheduled. Are you noticing that in your merchant portal that the UI is indicating the shipment is a draft and not in the scheduled state?

**Comment by dschnare** [comment]
I'll close this out since we are communicating via email in more detail.
